export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORY = 'GET_CATEGORY'
export const UP_CATEGORY = 'UP_CATEGORY'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const GET_EDITORIALS = 'GET_EDITORIALS'
export const GET_EDITORIAL = 'GET_EDITORIAL'
export const UP_EDITORIAL = 'UP_EDITORIAL'
export const EDIT_EDITORIAL = 'EDIT_EDITORIAL'
export const DELETE_EDITORIAL = 'DELETE_EDITORIAL'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const UP_PRODUCT = 'UP_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const GET_RECOMMENDS = 'GET_RECOMMENDS'

export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_USERS = 'GET_USERS'
export const GET_SELLERS = 'GET_SELLERS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART'
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const TOTAL_PRICE = 'TOTAL_PRICE'
